CREATE TABLE IF NOT EXISTS bookings (
id SERIAL PRIMARY KEY,
room_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
status VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS payments (
id SERIAL PRIMARY KEY,
booking_id BIGINT REFERENCES bookings(id),
amount NUMERIC(10,2) NOT NULL,
status VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);